// Lingua v1.0.17 language list.
// DeepL remains the safe core. Extended languages are routed server-side through
// Microsoft Translator / Google when one of those broad providers is configured.
// Provider credentials never ship in the desktop app.
export const LANGUAGES = [
  { code: "auto", name: "Auto detect" },
  { code: "bg", name: "Bulgarian (Български)" },
  { code: "cs", name: "Czech (Čeština)" },
  { code: "da", name: "Danish (Dansk)" },
  { code: "de", name: "German (Deutsch)" },
  { code: "el", name: "Greek (Ελληνικά)" },
  { code: "en", name: "English" },
  { code: "es", name: "Spanish (Español)" },
  { code: "et", name: "Estonian (Eesti)" },
  { code: "fi", name: "Finnish (Suomi)" },
  { code: "fr", name: "French (Français)" },
  { code: "hu", name: "Hungarian (Magyar)" },
  { code: "id", name: "Indonesian (Bahasa)" },
  { code: "it", name: "Italian (Italiano)" },
  { code: "ja", name: "Japanese (日本語)" },
  { code: "ko", name: "Korean (한국어)" },
  { code: "lt", name: "Lithuanian (Lietuvių)" },
  { code: "lv", name: "Latvian (Latviešu)" },
  { code: "no", name: "Norwegian (Norsk)" },
  { code: "nl", name: "Dutch (Nederlands)" },
  { code: "pl", name: "Polish (Polski)" },
  { code: "pt", name: "Portuguese (Português)" },
  { code: "ro", name: "Romanian (Română)" },
  { code: "ru", name: "Russian (Русский)" },
  { code: "sk", name: "Slovak (Slovenčina)" },
  { code: "sl", name: "Slovenian (Slovenščina)" },
  { code: "sv", name: "Swedish (Svenska)" },
  { code: "tr", name: "Turkish (Türkçe)" },
  { code: "uk", name: "Ukrainian (Українська)" },
  { code: "zh", name: "Chinese (中文)" },

  // Broad-provider languages (Microsoft Translator / Google).
  { code: "af", name: "Afrikaans" },
  { code: "sq", name: "Albanian (Shqip)" },
  { code: "am", name: "Amharic (አማርኛ)" },
  { code: "ar", name: "Arabic (العربية)" },
  { code: "hy", name: "Armenian (Հայերեն)" },
  { code: "az", name: "Azerbaijani (Azərbaycanca)" },
  { code: "bn", name: "Bangla (বাংলা)" },
  { code: "eu", name: "Basque (Euskara)" },
  { code: "fil", name: "Filipino" },
  { code: "gl", name: "Galician (Galego)" },
  { code: "ka", name: "Georgian (ქართული)" },
  { code: "gu", name: "Gujarati (ગુજરાતી)" },
  { code: "he", name: "Hebrew (עברית)" },
  { code: "hi", name: "Hindi (हिन्दी)" },
  { code: "is", name: "Icelandic (Íslenska)" },
  { code: "ga", name: "Irish (Gaeilge)" },
  { code: "kn", name: "Kannada (ಕನ್ನಡ)" },
  { code: "kk", name: "Kazakh (Қазақша)" },
  { code: "km", name: "Khmer (ខ្មែរ)" },
  { code: "lo", name: "Lao (ລາວ)" },
  { code: "ms", name: "Malay (Bahasa Melayu)" },
  { code: "ml", name: "Malayalam (മലയാളം)" },
  { code: "mt", name: "Maltese (Malti)" },
  { code: "mr", name: "Marathi (मराठी)" },
  { code: "my", name: "Myanmar / Burmese (မြန်မာ)" },
  { code: "ne", name: "Nepali (नेपाली)" },
  { code: "fa", name: "Persian (فارسی)" },
  { code: "pa", name: "Punjabi (ਪੰਜਾਬੀ)" },
  { code: "sr-Latn", name: "Serbian Latin (Srpski)" },
  { code: "sr-Cyrl", name: "Serbian Cyrillic (Српски)" },
  { code: "sw", name: "Swahili (Kiswahili)" },
  { code: "ta", name: "Tamil (தமிழ்)" },
  { code: "te", name: "Telugu (తెలుగు)" },
  { code: "th", name: "Thai (ไทย)" },
  { code: "ur", name: "Urdu (اردو)" },
  { code: "vi", name: "Vietnamese (Tiếng Việt)" },
  { code: "cy", name: "Welsh (Cymraeg)" },
  { code: "zu", name: "Zulu (isiZulu)" },
];

export const DEEPL_SUPPORTED: Record<string, string> = {
  bg: "BG", cs: "CS", da: "DA", de: "DE", el: "EL", en: "EN", es: "ES", et: "ET",
  fi: "FI", fr: "FR", hu: "HU", id: "ID", it: "IT", ja: "JA", ko: "KO", lt: "LT",
  lv: "LV", no: "NB", nl: "NL", pl: "PL", pt: "PT-PT", ro: "RO", ru: "RU", sk: "SK",
  sl: "SL", sv: "SV", tr: "TR", uk: "UK", zh: "ZH",
};
