const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('linguaDesktop', {
  getServerInfo: () => ipcRenderer.invoke('lingua:server-info'),
  login: (payload) => ipcRenderer.invoke('lingua:login', payload),
  logout: () => ipcRenderer.invoke('lingua:logout'),
  accountStatus: () => ipcRenderer.invoke('lingua:account-status'),
  removeDevice: (deviceId) => ipcRenderer.invoke('lingua:remove-device', { deviceId }),
  appInfo: () => ipcRenderer.invoke('lingua:app-info'),
  setPerformanceProfile: (profile) => ipcRenderer.invoke('lingua:set-performance-profile', { profile }),
  cacheStats: (partitions) => ipcRenderer.invoke('lingua:cache-stats', { partitions }),
  clearAppCache: (partitions) => ipcRenderer.invoke('lingua:clear-app-cache', { partitions }),
  clearInstanceCache: (partition) => ipcRenderer.invoke('lingua:clear-instance-cache', { partition }),
  applyProxy: (proxy, partitions) => ipcRenderer.invoke('lingua:apply-proxy', { proxy, partitions }),
  testProxy: (partition) => ipcRenderer.invoke('lingua:test-proxy', { partition }),
  checkUpdate: (channel) => ipcRenderer.invoke('lingua:check-update', { channel }),
  downloadUpdate: (payload) => ipcRenderer.invoke('lingua:download-update', payload),
  launchVerifiedUpdate: (filePath) => ipcRenderer.invoke('lingua:launch-verified-update', { filePath }),
  openDownloads: () => ipcRenderer.invoke('lingua:open-downloads'),
  openAdmin: () => ipcRenderer.invoke('lingua:open-admin'),
  redeemCode: (code) => ipcRenderer.invoke('lingua:redeem-code', { code }),
  translate: (payload) => ipcRenderer.invoke('lingua:translate', payload),
  voiceUsage: () => ipcRenderer.invoke('lingua:voice-usage'),
  voiceTranslate: (payload) => ipcRenderer.invoke('lingua:voice-translate', payload),
  providerStatus: () => ipcRenderer.invoke('lingua:provider-status'),
  openBilling: () => ipcRenderer.invoke('lingua:open-billing'),
  openExternal: (url) => ipcRenderer.invoke('lingua:open-external', url),
  launchSignal: () => ipcRenderer.invoke('lingua:launch-signal'),
  signalStatus: () => ipcRenderer.invoke('lingua:signal-status'),
  notifyUnread: (payload) => ipcRenderer.invoke('lingua:notify-unread', payload),
  warmService: (url, partition) => ipcRenderer.invoke('lingua:warm-service', { url, partition }),
  getPreloadPath: () => ipcRenderer.invoke('lingua:preload-path'),
  clearInstanceSession: (partition) => ipcRenderer.invoke('lingua:clear-instance-session', partition)
});
